spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
      bootstrap-servers: kafka:9092
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true